global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'online-shop'
    static_configs:
      - targets: ['web:${APP_PORT}']
    metrics_path: /metrics

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']